"""
Tourist visit logs from Supabase — both online "Schedule Visit" requests
and establishment-owner-entered walk-in logs.

Status lifecycle (online requests):
  pending   -> confirmed | declined   (establishment owner decision)
  confirmed -> completed | cancelled  (one-click "Mark arrived" check-in,
                                        or manual cancel)
  completed -> confirmed              (undo check-in, only when the
                                        completion came from check-in,
                                        i.e. arrived_at is set and the row
                                        isn't a manual walk-in log)

Manual walk-in logs (is_manual=True) are inserted directly as 'completed'
with arrived_at set — there's no request workflow for a log the owner is
entering after the fact.

Arrival reports to LTCATO are generated by aggregating completed logs
(see aggregate_logs_for_report / generate_and_submit_arrival_report)
instead of being typed by hand.
"""

from __future__ import annotations

from datetime import date, datetime, timedelta, timezone
from typing import Any

from services.supabase_client import get_supabase

VISIT_STATUSES = ("pending", "confirmed", "declined", "completed", "cancelled")
ACTIVE_STATUSES = ("pending", "confirmed")
VISITOR_CATEGORIES = ("day_tour", "overnight")
ORIGINS = ("this_city", "other_city", "other_province", "foreign")

_ALLOWED_TRANSITIONS = {
    "pending": ("confirmed", "declined"),
    "confirmed": ("cancelled",),  # confirmed -> completed only via check_in_visit()
}

# origin -> (male_count_key, female_count_key) in the shape arrival_reports expects
_ORIGIN_COUNT_KEYS = {
    "this_city": ("this_city_male", "this_city_female"),
    "other_city": ("other_city_male", "other_city_female"),
    "other_province": ("other_province_male", "other_province_female"),
    "foreign": ("foreign_male", "foreign_female"),
}
_ORIGIN_COUNT_KEYS_FLAT = tuple(
    key for pair in _ORIGIN_COUNT_KEYS.values() for key in pair
)

VISIT_FIELDS = (
    "id, tourist_spot_id, tourist_id, visitor_name, visitor_email, visitor_phone, "
    "visit_date, visit_time, party_size, notes, status, "
    "visitor_category, overnight_nights, origin, male_count, female_count, "
    "arrived_at, is_manual, logged_by, created_at, updated_at, "
    "tourist_spots(id, name, owner_id, lgu_id)"
)

_CREATE_ALLOWED = {
    "tourist_spot_id",
    "tourist_id",
    "visitor_name",
    "visitor_email",
    "visitor_phone",
    "visit_date",
    "visit_time",
    "party_size",
    "notes",
    "visitor_category",
    "overnight_nights",
    "origin",
    "male_count",
    "female_count",
}

_MANUAL_LOG_ALLOWED = _CREATE_ALLOWED

_DEMOGRAPHICS_ALLOWED = {
    "visitor_category",
    "overnight_nights",
    "origin",
    "male_count",
    "female_count",
}


def _normalize_visit_row(row: dict[str, Any]) -> dict[str, Any]:
    row["visitor_email"] = (row.get("visitor_email") or "").strip().lower() or None
    row["visitor_name"] = (row.get("visitor_name") or "").strip()
    row["party_size"] = int(row.get("party_size") or 1)
    if row.get("visitor_category") not in VISITOR_CATEGORIES:
        row["visitor_category"] = "day_tour"
    row["overnight_nights"] = int(row.get("overnight_nights") or 0)
    return row


def _apply_demographics(row: dict[str, Any], payload: dict[str, Any]) -> None:
    """Validate and set origin + gender counts — shared by the tourist-facing
    "Schedule Visit" request and the owner's manual walk-in log, since LTCATO
    needs this breakdown for arrival reports either way (see
    aggregate_logs_for_report)."""
    if payload.get("origin") not in ORIGINS:
        raise ValueError("Please tell us where the visitor is coming from.")
    if payload.get("male_count") in (None, ""):
        raise ValueError("Male count is required.")
    if payload.get("female_count") in (None, ""):
        raise ValueError("Female count is required.")
    row["origin"] = payload["origin"]
    row["male_count"] = int(payload["male_count"])
    row["female_count"] = int(payload["female_count"])


def _insert_visit_row(row: dict[str, Any]):
    """Insert into visit_schedules, tolerating a not-yet-migrated `source`
    column (pre-arrival_reports_v2.sql) by retrying without it."""
    try:
        return get_supabase().table("visit_schedules").insert(row).execute()
    except Exception as exc:
        if "source" in str(exc) and "source" in row:
            row = {k: v for k, v in row.items() if k != "source"}
            return get_supabase().table("visit_schedules").insert(row).execute()
        raise


def create_visit_schedule(payload: dict[str, Any]) -> dict[str, Any]:
    row = {k: payload[k] for k in _CREATE_ALLOWED if k in payload}
    row = _normalize_visit_row(row)
    if not row["visitor_name"]:
        raise ValueError("Visitor name is required.")
    _apply_demographics(row, payload)
    row["status"] = "pending"
    row["source"] = "scheduled"

    response = _insert_visit_row(row)
    data = response.data or []
    if not data:
        raise RuntimeError("Failed to save visit schedule.")
    return data[0]


def _verify_spot_owner(spot_id: int, owner_id: str) -> dict[str, Any]:
    response = (
        get_supabase()
        .table("tourist_spots")
        .select("id, lgu_id, owner_id")
        .eq("id", spot_id)
        .limit(1)
        .execute()
    )
    rows = response.data or []
    if not rows:
        raise ValueError("Establishment not found.")
    spot = rows[0]
    if str(spot.get("owner_id")) != str(owner_id):
        raise PermissionError("You can only manage your own establishment.")
    return spot


def create_manual_log(payload: dict[str, Any], *, owner_id: str) -> dict[str, Any]:
    spot_id = payload.get("tourist_spot_id")
    if not spot_id:
        raise ValueError("A tourist spot is required.")
    _verify_spot_owner(int(spot_id), owner_id)

    row = {k: payload[k] for k in _MANUAL_LOG_ALLOWED if k in payload}
    row = _normalize_visit_row(row)
    if not row["visitor_name"]:
        raise ValueError("Visitor name is required.")
    _apply_demographics(row, payload)
    row["status"] = "completed"
    row["is_manual"] = True
    row["source"] = "walk_in"
    row["logged_by"] = owner_id
    row["arrived_at"] = datetime.now(timezone.utc).isoformat()

    response = _insert_visit_row(row)
    data = response.data or []
    if not data:
        raise RuntimeError("Failed to save manual log.")
    return data[0]


def list_visits_for_spot(
    spot_id: int, *, status: str | None = None, limit: int = 200
) -> list[dict[str, Any]]:
    query = (
        get_supabase()
        .table("visit_schedules")
        .select(VISIT_FIELDS)
        .eq("tourist_spot_id", spot_id)
    )
    if status:
        query = query.eq("status", status)
    response = query.order("visit_date", desc=True).limit(limit).execute()
    return response.data or []


def _spot_ids_for_owner(owner_id: str) -> set[int]:
    from services.spots import list_spots_for_dashboard

    spots = list_spots_for_dashboard(owner_id=owner_id, limit=50)
    return {int(s["id"]) for s in spots if s.get("id") is not None}


def list_visits_for_owner(
    owner_id: str,
    *,
    status: str | None = None,
    q: str | None = None,
    limit: int = 200,
) -> list[dict[str, Any]]:
    """Online 'Schedule Visit' requests only (excludes manual walk-in logs —
    those belong on the Logs page, see list_logs_for_owner)."""
    spot_ids = _spot_ids_for_owner(owner_id)
    if not spot_ids:
        return []
    query = (
        get_supabase()
        .table("visit_schedules")
        .select(VISIT_FIELDS)
        .in_("tourist_spot_id", list(spot_ids))
        .eq("is_manual", False)
    )
    if status:
        query = query.eq("status", status)
    if q:
        term = q.strip()
        if term:
            query = query.or_(f"visitor_name.ilike.%{term}%,visitor_email.ilike.%{term}%")
    response = query.order("visit_date", desc=True).limit(limit).execute()
    return response.data or []


def list_logs_for_owner(
    owner_id: str,
    *,
    spot_id: int | None = None,
    q: str | None = None,
    date_from: str | None = None,
    date_to: str | None = None,
    limit: int = 500,
) -> list[dict[str, Any]]:
    spot_ids = _spot_ids_for_owner(owner_id)
    if spot_id is not None:
        spot_ids &= {int(spot_id)}
    if not spot_ids:
        return []
    query = (
        get_supabase()
        .table("visit_schedules")
        .select(VISIT_FIELDS)
        .in_("tourist_spot_id", list(spot_ids))
    )
    if q:
        term = q.strip()
        if term:
            query = query.or_(f"visitor_name.ilike.%{term}%,visitor_email.ilike.%{term}%")
    if date_from:
        query = query.gte("visit_date", date_from)
    if date_to:
        query = query.lte("visit_date", date_to)
    response = query.order("visit_date", desc=True).limit(limit).execute()
    return response.data or []


def list_visits_for_tourist(
    tourist_id: str, email: str, *, limit: int = 100
) -> list[dict[str, Any]]:
    email = (email or "").strip().lower()
    response = (
        get_supabase()
        .table("visit_schedules")
        .select(VISIT_FIELDS)
        .or_(f"tourist_id.eq.{tourist_id},visitor_email.eq.{email}")
        .order("visit_date", desc=True)
        .limit(limit)
        .execute()
    )
    return response.data or []


def update_visit_status(visit_id: int, new_status: str, *, owner_id: str) -> None:
    response = (
        get_supabase()
        .table("visit_schedules")
        .select("id, status, tourist_spots(owner_id)")
        .eq("id", visit_id)
        .execute()
    )
    rows = response.data or []
    if not rows:
        raise ValueError("Visit request not found.")
    row = rows[0]
    spot = row.get("tourist_spots") or {}
    if str(spot.get("owner_id")) != str(owner_id):
        raise PermissionError("You can only manage visits for your own establishment.")

    current = row.get("status")
    allowed = _ALLOWED_TRANSITIONS.get(current, ())
    if new_status not in allowed:
        raise ValueError(
            f"Cannot change a {current} visit request to {new_status}."
        )

    get_supabase().table("visit_schedules").update(
        {"status": new_status, "updated_at": datetime.now(timezone.utc).isoformat()}
    ).eq("id", visit_id).execute()


def _load_owned_visit(visit_id: int, *, owner_id: str) -> dict[str, Any]:
    response = (
        get_supabase()
        .table("visit_schedules")
        .select("id, status, is_manual, arrived_at, tourist_spots(owner_id)")
        .eq("id", visit_id)
        .execute()
    )
    rows = response.data or []
    if not rows:
        raise ValueError("Visit request not found.")
    row = rows[0]
    spot = row.get("tourist_spots") or {}
    if str(spot.get("owner_id")) != str(owner_id):
        raise PermissionError("You can only manage visits for your own establishment.")
    return row


def check_in_visit(visit_id: int, *, owner_id: str) -> dict[str, Any]:
    row = _load_owned_visit(visit_id, owner_id=owner_id)
    if row.get("status") != "confirmed":
        raise ValueError("Only confirmed visits can be marked as arrived.")

    now = datetime.now(timezone.utc).isoformat()
    response = (
        get_supabase()
        .table("visit_schedules")
        .update({"status": "completed", "arrived_at": now, "updated_at": now})
        .eq("id", visit_id)
        .execute()
    )
    data = response.data or []
    if not data:
        raise RuntimeError("Failed to check in visit.")
    return data[0]


def undo_check_in(visit_id: int, *, owner_id: str) -> None:
    row = _load_owned_visit(visit_id, owner_id=owner_id)
    if row.get("is_manual") or row.get("status") != "completed" or not row.get("arrived_at"):
        raise ValueError("This visit cannot be undone.")

    get_supabase().table("visit_schedules").update(
        {
            "status": "confirmed",
            "arrived_at": None,
            "updated_at": datetime.now(timezone.utc).isoformat(),
        }
    ).eq("id", visit_id).execute()


def update_visit_demographics(
    visit_id: int,
    *,
    owner_id: str,
    visitor_category: str | None,
    overnight_nights: int | None,
    origin: str | None,
    male_count: int | None,
    female_count: int | None,
) -> None:
    row = _load_owned_visit(visit_id, owner_id=owner_id)
    del row  # ownership already verified

    payload: dict[str, Any] = {}
    if visitor_category in VISITOR_CATEGORIES:
        payload["visitor_category"] = visitor_category
    payload["overnight_nights"] = int(overnight_nights or 0)
    payload["origin"] = origin if origin in ORIGINS else None
    payload["male_count"] = int(male_count) if male_count not in (None, "") else None
    payload["female_count"] = int(female_count) if female_count not in (None, "") else None
    payload["updated_at"] = datetime.now(timezone.utc).isoformat()

    get_supabase().table("visit_schedules").update(payload).eq("id", visit_id).execute()


def aggregate_logs_for_report(
    owner_id: str,
    spot_id: int,
    *,
    date_from: str,
    date_to: str,
    visitor_category: str,
) -> dict[str, Any]:
    _verify_spot_owner(spot_id, owner_id)

    response = (
        get_supabase()
        .table("visit_schedules")
        .select(
            "party_size, visitor_category, overnight_nights, origin, male_count, female_count"
        )
        .eq("tourist_spot_id", spot_id)
        .eq("status", "completed")
        .eq("visitor_category", visitor_category)
        .gte("visit_date", date_from)
        .lte("visit_date", date_to)
        .execute()
    )
    rows = response.data or []

    counts = {
        "this_city_male": 0,
        "this_city_female": 0,
        "other_city_male": 0,
        "other_city_female": 0,
        "other_province_male": 0,
        "other_province_female": 0,
        "foreign_male": 0,
        "foreign_female": 0,
    }
    overnight_nights = 0
    unclassified_count = 0
    for row in rows:
        origin = row.get("origin")
        keys = _ORIGIN_COUNT_KEYS.get(origin)
        if keys:
            male_key, female_key = keys
            counts[male_key] += int(row.get("male_count") or 0)
            counts[female_key] += int(row.get("female_count") or 0)
        else:
            # No residence on record — the official Excel template has no
            # cell for this, so it can't appear in the breakdown. Surface it
            # as a count rather than silently dropping these visitors.
            unclassified_count += int(row.get("party_size") or 0)
        overnight_nights += int(row.get("overnight_nights") or 0)

    counts["overnight_nights"] = overnight_nights
    counts["visit_count"] = len(rows)
    counts["unclassified_count"] = unclassified_count
    return counts


def generate_and_submit_arrival_report(
    *,
    owner_id: str,
    spot_id: int,
    visitor_category: str,
    report_type: str,
    date_from: str,
    date_to: str,
) -> tuple[dict[str, Any], int]:
    """Returns (report_row, unclassified_count) — the latter is the number
    of visitors with no residence on record, excluded from the breakdown
    but not silently lost (see aggregate_logs_for_report)."""
    from services.arrival_reports import create_arrival_report

    spot = _verify_spot_owner(spot_id, owner_id)
    aggregated = aggregate_logs_for_report(
        owner_id, spot_id, date_from=date_from, date_to=date_to, visitor_category=visitor_category
    )
    aggregated.pop("visit_count", None)
    unclassified_count = aggregated.pop("unclassified_count", 0)

    payload = {
        "tourist_spot_id": spot_id,
        "lgu_id": spot.get("lgu_id"),
        "submitted_by": owner_id,
        "report_type": report_type,
        "report_date": date_to,
        "visitor_category": visitor_category,
        "status": "submitted",
        **aggregated,
    }
    return create_arrival_report(payload), unclassified_count


# ---------------------------------------------------------------------------
# Phase 2: automatic aggregation — LGU/owner see live daily/weekly/monthly
# totals computed directly from completed visit_schedules rows. No owner
# action creates a report; viewing is a pure read/aggregate (idempotent by
# construction — nothing is written to the database by these functions).
# ---------------------------------------------------------------------------

_VISIT_AGGREGATE_FIELDS = (
    "id, tourist_spot_id, visit_date, party_size, visitor_category, "
    "overnight_nights, origin, male_count, female_count, "
    "tourist_spots(id, name, code)"
)


def list_completed_visits(
    *,
    spot_ids: list[int] | None = None,
    lgu_id: int | None = None,
    date_from: str,
    date_to: str,
    visitor_category: str | None = None,
    limit: int = 2000,
) -> list[dict[str, Any]]:
    """Raw completed visit_schedules rows in a date range, scoped to either
    an explicit list of spot ids (owner's own view) or a whole LGU."""
    if spot_ids is None:
        if lgu_id is None:
            raise ValueError("Either spot_ids or lgu_id is required.")
        from services.spots import list_spots_for_dashboard

        spots = list_spots_for_dashboard(lgu_id=lgu_id, limit=500)
        spot_ids = [int(s["id"]) for s in spots if s.get("id") is not None]

    if not spot_ids:
        return []

    query = (
        get_supabase()
        .table("visit_schedules")
        .select(_VISIT_AGGREGATE_FIELDS)
        .in_("tourist_spot_id", spot_ids)
        .eq("status", "completed")
        .gte("visit_date", date_from)
        .lte("visit_date", date_to)
    )
    if visitor_category:
        query = query.eq("visitor_category", visitor_category)
    response = query.order("visit_date").limit(limit).execute()
    return response.data or []


def aggregate_visits_by_spot(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Group completed visit rows into one summary row per tourist spot —
    same shape the LGU consolidation flow has always used."""
    by_spot: dict[int, dict[str, Any]] = {}
    for row in rows:
        sid = row.get("tourist_spot_id")
        if sid is None:
            continue
        sid = int(sid)
        if sid not in by_spot:
            spot = row.get("tourist_spots") or {}
            by_spot[sid] = {
                "tourist_spot_id": sid,
                "spot_name": spot.get("name") or f"Spot #{sid}",
                "spot_code": spot.get("code"),
                "report_count": 0,
                "unclassified_count": 0,
                "overnight_nights": 0,
                **{k: 0 for k in _ORIGIN_COUNT_KEYS_FLAT},
            }
        entry = by_spot[sid]
        entry["report_count"] += 1
        entry["overnight_nights"] += int(row.get("overnight_nights") or 0)
        keys = _ORIGIN_COUNT_KEYS.get(row.get("origin"))
        if keys:
            male_key, female_key = keys
            entry[male_key] += int(row.get("male_count") or 0)
            entry[female_key] += int(row.get("female_count") or 0)
        else:
            entry["unclassified_count"] += int(row.get("party_size") or 0)

    results = list(by_spot.values())
    for entry in results:
        entry["total_visitors"] = sum(entry[k] for k in _ORIGIN_COUNT_KEYS_FLAT)
    return sorted(results, key=lambda x: x["spot_name"])


def aggregate_visits_by_day(
    rows: list[dict[str, Any]], *, date_from: str, date_to: str
) -> list[dict[str, Any]]:
    """Group completed visit rows into one row per calendar date (zero-filled
    for dates with no activity), so a week/month view shows a real daily
    breakdown instead of a single number."""
    by_day: dict[str, dict[str, Any]] = {}
    start = date.fromisoformat(date_from)
    end = date.fromisoformat(date_to)
    d = start
    while d <= end:
        iso = d.isoformat()
        by_day[iso] = {"date": iso, "day_tour_total": 0, "overnight_total": 0, "total": 0}
        d += timedelta(days=1)

    for row in rows:
        iso = str(row.get("visit_date"))[:10]
        entry = by_day.get(iso)
        if entry is None:
            continue
        party = int(row.get("party_size") or 0)
        entry["total"] += party
        if row.get("visitor_category") == "overnight":
            entry["overnight_total"] += party
        else:
            entry["day_tour_total"] += party

    return [by_day[k] for k in sorted(by_day.keys())]


def consolidate_lgu_visits_for_month(
    lgu_id: int, *, year: int, month: int, visitor_category: str
) -> list[dict[str, Any]]:
    """Per-spot totals for a full month, automatically aggregated from
    completed visit_schedules — replaces the old owner-submitted-reports
    based consolidation. Excludes spots that already have a submitted
    monthly arrival_reports row for this period, same as before."""
    from calendar import monthrange

    first_day = date(year, month, 1)
    last_day = date(year, month, monthrange(year, month)[1])

    rows = list_completed_visits(
        lgu_id=lgu_id,
        date_from=first_day.isoformat(),
        date_to=last_day.isoformat(),
        visitor_category=visitor_category,
    )
    spot_rows = aggregate_visits_by_spot(rows)

    already_submitted = (
        get_supabase()
        .table("arrival_reports")
        .select("tourist_spot_id")
        .eq("lgu_id", lgu_id)
        .eq("report_type", "monthly")
        .eq("visitor_category", visitor_category)
        .gte("report_date", first_day.isoformat())
        .lte("report_date", last_day.isoformat())
        .execute()
    )
    already_submitted_ids = {
        int(r["tourist_spot_id"])
        for r in (already_submitted.data or [])
        if r.get("tourist_spot_id") is not None
    }

    return [r for r in spot_rows if r["tourist_spot_id"] not in already_submitted_ids]


def list_previous_visitor_emails_for_lgu(lgu_id: int, *, limit: int = 300) -> list[str]:
    response = (
        get_supabase()
        .table("visit_schedules")
        .select("visitor_email, tourist_spots!inner(lgu_id)")
        .eq("status", "completed")
        .eq("tourist_spots.lgu_id", lgu_id)
        .not_.is_("visitor_email", "null")
        .limit(limit)
        .execute()
    )
    rows = response.data or []
    emails = {r["visitor_email"] for r in rows if r.get("visitor_email")}
    return sorted(emails)[:limit]


def get_spot_owner_email(spot_id: int) -> str | None:
    spot_res = (
        get_supabase()
        .table("tourist_spots")
        .select("owner_id")
        .eq("id", spot_id)
        .limit(1)
        .execute()
    )
    spot_rows = spot_res.data or []
    owner_id = spot_rows[0].get("owner_id") if spot_rows else None
    if not owner_id:
        return None

    profile_res = (
        get_supabase()
        .table("profiles")
        .select("email")
        .eq("id", owner_id)
        .limit(1)
        .execute()
    )
    profile_rows = profile_res.data or []
    return profile_rows[0].get("email") if profile_rows else None
