-- Run in Supabase SQL editor. Bulk-inserts 15 sample events, in the same
-- style as the events already in the table (e.g. "Anilag 2026",
-- "Sampaguita Festival 2026"), so the dashboard/site have realistic data
-- to browse and demo against instead of just the handful of existing rows.
--
-- approval_status is 'approved' and visibility is 'public' for every row so
-- they all show up immediately on the public site; event_status is
-- 'upcoming' for all of them since services/events.py recomputes the real
-- upcoming/ongoing/finished label from start_date/end_date on every read
-- regardless of what's stored here (see _compute_event_status) — a couple
-- of the rows below use past dates on purpose so they'll display as
-- "finished" once loaded.
--
-- No cover_image/banner_image is set, so the site falls back to its
-- default placeholder image for these — swap in real image URLs later via
-- the dashboard's event edit form if needed.
--
-- created_by/approved_by are left NULL (nullable columns) since these are
-- being added directly, not through a dashboard user's session.
--
-- Note: there's no UNIQUE constraint on slug, so running this script twice
-- will insert duplicates — remove rows you've already added before
-- re-running, rather than relying on this to dedupe.

INSERT INTO events (
  title, slug, short_description, full_description, category, subcategory,
  event_status, visibility, organizer, contact_person, theme, tagline,
  tourism_campaign_type, start_date, end_date, venue, venue_name, venue_type,
  lgu_id, barangay, overview, expected_visitors, approval_status
)
VALUES
  (
    'Kalabasa Festival 2026',
    'kalabasa-festival-2026',
    'Alaminos'' annual squash harvest festival celebrating the town''s signature crop with street dancing, food stalls, and a grand market fair.',
    '<p>The Kalabasa (Squash) Festival is Alaminos, Laguna''s way of giving thanks for a bountiful harvest season. The week-long celebration features a street dancing competition where contingents from every barangay perform routines inspired by planting and harvesting, a squash-themed cooking contest, and a night market selling local produce and delicacies made from squash.</p><p>Visitors can also join guided farm tours to nearby squash plantations and sample kalabasa-based dishes prepared by local home cooks and restaurants.</p>',
    'food',
    'Harvest Fair',
    'upcoming',
    'public',
    'Alaminos Municipal Tourism Office',
    'Alaminos Tourism Office',
    'Sagana at Masaganang Ani',
    '"Harvest of Gold, Pride of Alaminos"',
    'LGU',
    '2026-10-12',
    '2026-10-18',
    'Alaminos Public Plaza',
    'Alaminos Public Plaza',
    'outdoor',
    7,
    'Poblacion',
    'An annual harvest festival showcasing Alaminos'' squash farming heritage through street dancing, food fairs, and community celebrations.',
    5000,
    'approved'
  ),
  (
    'Bay Fluvial Parade 2026',
    'bay-fluvial-parade-2026',
    'A colorful fluvial procession along the Bay River honoring the town''s patron saint, followed by a lakeside food and crafts fair.',
    '<p>The Bay Fluvial Parade brings together decorated boats carrying the image of the town''s patron saint in a procession along the river leading to Laguna de Bay. The event draws devotees and tourists alike, with the riverbanks lined with food stalls, local handicraft vendors, and live cultural performances.</p><p>The celebration closes with an evening fireworks display over the lake.</p>',
    'cultural',
    'Fluvial Procession',
    'upcoming',
    'public',
    'Bay Municipal Tourism Office',
    'Bay Tourism Office',
    'Pananampalataya at Pagkakaisa',
    '"Faith Flowing Through Bay"',
    'LGU',
    '2026-09-05',
    '2026-09-12',
    'Bay River Boardwalk',
    'Bay River Boardwalk',
    'outdoor',
    8,
    'Poblacion',
    'A traditional fluvial procession and lakeside festival celebrating Bay''s patron saint and its ties to Laguna de Bay.',
    3000,
    'approved'
  ),
  (
    'Biñan Founding Anniversary Grand Fair 2026',
    'binan-founding-anniversary-grand-fair-2026',
    'Biñan City marks its founding anniversary with a grand trade fair, concerts, and heritage exhibits at the historic Plaza Zamora.',
    '<p>Biñan City celebrates its founding anniversary with a month-long series of activities anchored on a grand trade and livelihood fair at Plaza Zamora, near the historic Alberto Mansion. Highlights include nightly concerts featuring local and guest artists, a heritage photo exhibit on Biñan''s Rizalista history, and a food park showcasing local restaurants and MSMEs.</p>',
    'festival',
    'Founding Anniversary',
    'upcoming',
    'public',
    'Biñan City Tourism Office',
    'Biñan Tourism Office',
    'Bayan ng Pag-asa, Bayan ng Pagbabago',
    '"Isang Bayan, Isang Pagdiriwang"',
    'National',
    '2026-12-01',
    '2026-12-15',
    'Plaza Zamora',
    'Plaza Zamora',
    'outdoor',
    9,
    'Poblacion',
    'Biñan City''s annual founding anniversary celebration featuring trade fairs, concerts, and heritage programs at Plaza Zamora.',
    15000,
    'approved'
  ),
  (
    'Cabuyao Trade & Industry Expo 2026',
    'cabuyao-trade-industry-expo-2026',
    'A three-day industry and livelihood expo showcasing Cabuyao''s growing manufacturing sector alongside local MSMEs and startups.',
    '<p>The Cabuyao Trade & Industry Expo gathers the city''s manufacturing and industrial partners together with local micro, small, and medium enterprises for a three-day showcase of products, job fairs, and investment forums. Panel discussions with local industry leaders and government officials round out the program, alongside a food and lifestyle bazaar open to the public.</p>',
    'trade',
    'Industry Expo',
    'upcoming',
    'public',
    'Cabuyao City Tourism & Investment Office',
    'Cabuyao Tourism Office',
    'Industriya Para sa Kaunlaran',
    '"Building Tomorrow, Today"',
    'Provincial',
    '2026-11-06',
    '2026-11-08',
    'Cabuyao City Sports Complex',
    'Cabuyao City Sports Complex',
    'indoor',
    10,
    'Poblacion Uno',
    'A city-wide trade and industry expo highlighting Cabuyao''s manufacturing growth alongside local entrepreneurship.',
    8000,
    'approved'
  ),
  (
    'Calauan Harvest Fair 2026',
    'calauan-harvest-fair-2026',
    'A rice and coconut harvest fair celebrating Calauan''s agricultural roots with farm-to-table cooking demos and a farmers'' market.',
    '<p>The Calauan Harvest Fair brings farmers, cooperatives, and home cooks together to celebrate the town''s rice and coconut harvest. The fair features a farmers'' market with fresh produce direct from local fields, cooking demonstrations from municipal nutrition officers, and a friendly harvest-themed games competition for barangay teams.</p>',
    'food',
    'Harvest Fair',
    'upcoming',
    'public',
    'Calauan Municipal Tourism Office',
    'Calauan Tourism Office',
    'Ani at Pasasalamat',
    '"From Our Fields to Your Table"',
    'LGU',
    '2026-08-10',
    '2026-08-12',
    'Calauan Municipal Grounds',
    'Calauan Municipal Grounds',
    'outdoor',
    12,
    'Poblacion',
    'An agricultural harvest fair celebrating Calauan''s rice and coconut farming communities.',
    2500,
    'approved'
  ),
  (
    'Cavinti Adventure Fest 2026',
    'cavinti-adventure-fest-2026',
    'An outdoor sports festival at Cavinti''s Bunga Falls and Caliraya Lake featuring whitewater rafting, kayaking, and canyoneering side trips.',
    '<p>Cavinti Adventure Fest turns the town''s waterfalls and lakes into a weekend playground for outdoor enthusiasts. Activities include guided whitewater rafting down the Cavinti River, kayaking clinics at Caliraya Lake, and canyoneering side trips to Bunga Falls, alongside a camping village and bonfire nights for participants.</p>',
    'adventure',
    'Outdoor Sports',
    'upcoming',
    'public',
    'Cavinti Municipal Tourism Office',
    'Cavinti Tourism Office',
    'Kalikasan at Kasiyahan',
    '"Chase the Falls, Ride the Lake"',
    'Provincial',
    '2026-10-24',
    '2026-10-26',
    'Bunga Falls Adventure Park',
    'Bunga Falls Adventure Park',
    'outdoor',
    13,
    'Anglas',
    'An adventure sports weekend at Cavinti''s waterfalls and lakes featuring rafting, kayaking, and canyoneering.',
    4000,
    'approved'
  ),
  (
    'Famy Founding Fiesta 2026',
    'famy-founding-fiesta-2026',
    'Famy''s founding anniversary celebration with a homecoming parade, cultural night, and a hometown basketball league finals.',
    '<p>Famy''s Founding Fiesta welcomes balikbayans and neighboring townsfolk with a homecoming parade led by the mayor and local officials, a cultural night showcasing traditional Tagalog folk dances, and the season-ending finals of the town''s inter-barangay basketball league.</p>',
    'festival',
    'Founding Anniversary',
    'upcoming',
    'public',
    'Famy Municipal Tourism Office',
    'Famy Tourism Office',
    'Pagkakaisa ng Bayan',
    '"Tahanan Kahit Saan Man Tayo Magpunta"',
    'LGU',
    '2026-07-14',
    '2026-07-16',
    'Famy Municipal Plaza',
    'Famy Municipal Plaza',
    'outdoor',
    14,
    'Poblacion',
    'Famy''s annual founding anniversary celebration bringing the community together for a homecoming parade and cultural program.',
    1800,
    'approved'
  ),
  (
    'Kalayaan Lake Fest 2026',
    'kalayaan-lake-fest-2026',
    'A lakeside festival at Caliraya honoring Kalayaan''s hydropower heritage with boat races, a fun run, and an evening lantern float.',
    '<p>Kalayaan Lake Fest celebrates the town''s ties to the Caliraya-Lumot watershed and its hydroelectric heritage. The festival includes dragon boat races on Caliraya Lake, a 5K fun run around the reservoir, and closes with an evening lantern float on the water paired with a fireworks display.</p>',
    'adventure',
    'Lake Festival',
    'upcoming',
    'public',
    'Kalayaan Municipal Tourism Office',
    'Kalayaan Tourism Office',
    'Enerhiya at Kalikasan',
    '"Lights on the Lake"',
    'Provincial',
    '2026-11-14',
    '2026-11-16',
    'Caliraya Lake Resort',
    'Caliraya Lake Resort',
    'outdoor',
    15,
    'Sampaloc',
    'A lakeside celebration of Kalayaan''s hydropower heritage featuring boat races and a lantern float on Caliraya Lake.',
    3500,
    'approved'
  ),
  (
    'Liliw Tsinelas & Crafts Festival 2026',
    'liliw-tsinelas-crafts-festival-2026',
    'Liliw''s signature footwear and handicrafts festival, showcasing the town''s famous tsinelas-making industry through a grand market walk.',
    '<p>Known as the "Tsinelas Capital of the Philippines," Liliw celebrates its footwear-making heritage with a festival built around its famous market street lined with slipper and handicraft shops. The event features a tsinelas design competition, live demonstrations by local artisans, and a heritage walk highlighting the town''s Spanish-era church and ancestral houses.</p>',
    'arts',
    'Local Craft Fair',
    'upcoming',
    'public',
    'Liliw Municipal Tourism Office',
    'Liliw Tourism Office',
    'Sining at Kasanayan',
    '"Every Step Tells a Story"',
    'Provincial',
    '2026-10-30',
    '2026-11-01',
    'Liliw Market Street',
    'Liliw Market Street',
    'outdoor',
    16,
    'Poblacion',
    'A festival celebrating Liliw''s tsinelas-making tradition through craft demonstrations, a design competition, and a heritage walk.',
    6000,
    'approved'
  ),
  (
    'Los Baños Eco-Tourism Week 2026',
    'los-banos-eco-tourism-week-2026',
    'A week-long celebration of Los Baños'' natural attractions with guided Mt. Makiling hikes, hot spring tours, and a science-tourism forum with UPLB.',
    '<p>Los Baños Eco-Tourism Week highlights the town''s reputation as the "National Center for Science and Technology" and its natural attractions at the foot of Mt. Makiling. The week includes guided forest hikes, tours of local hot spring resorts, and a science-tourism forum in partnership with the University of the Philippines Los Baños showcasing research on the Makiling forest reserve.</p>',
    'adventure',
    'Eco-Tourism',
    'upcoming',
    'public',
    'Los Baños Municipal Tourism Office',
    'Los Baños Tourism Office',
    'Agham, Kalikasan, Kabuhayan',
    '"Where Nature Meets Discovery"',
    'National',
    '2026-09-08',
    '2026-09-14',
    'Mt. Makiling Forest Reserve',
    'Mt. Makiling Forest Reserve',
    'outdoor',
    3,
    'Batong Malake',
    'A week-long eco-tourism celebration of Los Baños'' hot springs, forests, and science-tourism partnerships around Mt. Makiling.',
    7000,
    'approved'
  ),
  (
    'Luisiana Coffee Festival 2026',
    'luisiana-coffee-festival-2026',
    'A celebration of Luisiana''s upland coffee farms with barista showcases, farm tours, and a mountain coffee tasting trail.',
    '<p>Nestled at the foot of Mt. Banahaw, Luisiana''s Coffee Festival celebrates the town''s growing coffee farming community. Visitors can join guided farm tours to upland coffee plantations, watch local barista showcases, and sample brews along a coffee tasting trail set up around the town plaza.</p>',
    'food',
    'Coffee Festival',
    'upcoming',
    'public',
    'Luisiana Municipal Tourism Office',
    'Luisiana Tourism Office',
    'Kape ng Bundok',
    '"Brewed at the Foot of Banahaw"',
    'LGU',
    '2026-12-05',
    '2026-12-07',
    'Luisiana Municipal Plaza',
    'Luisiana Municipal Plaza',
    'outdoor',
    18,
    'Poblacion',
    'A coffee-themed festival highlighting Luisiana''s upland coffee farms near Mt. Banahaw.',
    2200,
    'approved'
  ),
  (
    'Lumban Embroidery & Arts Fair 2026',
    'lumban-embroidery-arts-fair-2026',
    'A showcase of Lumban''s world-renowned barong tagalog embroidery, featuring live stitching demonstrations and a fashion show.',
    '<p>Lumban is celebrated as the "Embroidery Capital of the Philippines," and this fair puts its master embroiderers front and center. The event includes live hand-embroidery demonstrations, a barong tagalog and filipiniana fashion show, and a marketplace where visitors can order custom pieces directly from local ateliers.</p>',
    'arts',
    'Embroidery Fair',
    'upcoming',
    'public',
    'Lumban Municipal Tourism Office',
    'Lumban Tourism Office',
    'Sining ng Burda',
    '"Threads of Heritage"',
    'Provincial',
    '2026-11-20',
    '2026-11-22',
    'Lumban Municipal Gymnasium',
    'Lumban Municipal Gymnasium',
    'indoor',
    19,
    'Poblacion',
    'A fair celebrating Lumban''s renowned barong tagalog embroidery craft through live demonstrations and a fashion show.',
    3200,
    'approved'
  ),
  (
    'Mabitac Founding Anniversary 2026',
    'mabitac-founding-anniversary-2026',
    'Mabitac''s founding anniversary celebration honoring the historic Battle of Mabitac with a reenactment and community fair.',
    '<p>Mabitac commemorates its founding with a program centered on the historic Battle of Mabitac against American forces in 1899, including a reenactment by local youth groups, a wreath-laying ceremony at the town''s historical marker, and a community fair with local food and products.</p>',
    'festival',
    'Founding Anniversary',
    'upcoming',
    'public',
    'Mabitac Municipal Tourism Office',
    'Mabitac Tourism Office',
    'Bayani at Kasaysayan',
    '"Alaala ng Tagumpay"',
    'LGU',
    '2026-06-04',
    '2026-06-04',
    'Mabitac Municipal Plaza',
    'Mabitac Municipal Plaza',
    'outdoor',
    20,
    'Poblacion',
    'A founding anniversary program in Mabitac commemorating the historic Battle of Mabitac.',
    1500,
    'approved'
  ),
  (
    'Nagcarlan Underground Cemetery Heritage Walk 2026',
    'nagcarlan-underground-cemetery-heritage-walk-2026',
    'A guided heritage tour of the Nagcarlan Underground Cemetery and nearby colonial-era landmarks, paired with an evening cultural show.',
    '<p>This heritage walk takes visitors through the Nagcarlan Underground Cemetery, one of only two of its kind in the Philippines, along with a tour of the town''s Spanish-era church and ancestral houses. The day closes with an evening cultural show featuring local theater groups performing pieces on Nagcarlan''s revolutionary history.</p>',
    'cultural',
    'Heritage Walk',
    'upcoming',
    'public',
    'Nagcarlan Municipal Tourism Office',
    'Nagcarlan Tourism Office',
    'Pamana at Kasaysayan',
    '"Walk Through History"',
    'Provincial',
    '2026-10-15',
    '2026-10-15',
    'Nagcarlan Underground Cemetery',
    'Nagcarlan Underground Cemetery',
    'outdoor',
    23,
    'Bambang',
    'A heritage tour of the Nagcarlan Underground Cemetery and surrounding colonial landmarks.',
    1200,
    'approved'
  ),
  (
    'Pagsanjan Bangkero Festival 2026',
    'pagsanjan-bangkero-festival-2026',
    'Pagsanjan''s flagship festival honoring its boatmen with a colorful fluvial parade down the Bumbungan River ahead of the falls.',
    '<p>The Bangkero (Boatman) Festival is Pagsanjan''s way of paying tribute to the skilled boatmen who guide visitors through the famous Pagsanjan Falls rapids. The festival features a fluvial parade of decorated boats down the Bumbungan River, a street dancing competition, and demonstrations of traditional boat poling techniques used on the falls run.</p>',
    'cultural',
    'Fluvial Parade',
    'upcoming',
    'public',
    'Pagsanjan Municipal Tourism Office',
    'Pagsanjan Tourism Office',
    'Parangal sa mga Bangkero',
    '"Riding the Rapids, Honoring the Boatmen"',
    'National',
    '2026-11-29',
    '2026-12-01',
    'Pagsanjan Falls',
    'Pagsanjan Falls',
    'outdoor',
    25,
    'Poblacion',
    'Pagsanjan''s flagship festival honoring the town''s boatmen with a river parade and street dancing.',
    10000,
    'approved'
  );
